[package]
name = "hello-http"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = "0.6.11"
eyre = "0.6.8"
serde = { version = "1.0.155", features = ["derive"] }
tokio = { version = "1.25.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "signal",
] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
