name: cargo

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cargo.yml
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cargo.yml
      - Cargo.toml
      - Cargo.lock

jobs:
  check-unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read nightly toolchain
        id: toolchain
        uses: juliangruber/read-file-action@v1
        with:
          path: ./rust-nightly-toolchain.txt
      - name: Install Rust nightly toolchain
        run: rustup toolchain install ${{ steps.toolchain.outputs.content }}
      - run: echo "RUSTUP_TOOLCHAIN=${{ steps.toolchain.outputs.content }}" >> $GITHUB_ENV
      - uses: Swatinem/rust-cache@v2
      - run: cargo install --locked cargo-udeps@0.1.35
      - run: cargo +${{ steps.toolchain.outputs.content }} udeps --all-targets
