name: check-lockfiles

on:
  push:
    paths:
      - Cargo.lock
      - recipe.json
  pull_request:
    branches: [main]
    paths:
      - Cargo.lock
      - recipe.json

jobs:
  check-recipe-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2
        with:
          key: "cargo-chef"
      - run: cargo install --version 0.1.51 cargo-chef
      - name: Make the latest `recipe.json` with `cargo chef`
        run: cargo chef prepare --recipe-path recipe.json
      - id: recipe-unchanged
        run: |
          if git diff --quiet HEAD recipe.json; then
            echo "::set-output name=recipe_different::false"
          else
            echo "::set-output name=recipe_different::true"
          fi
      - if: steps.recipe-unchanged.outputs.recipe_different == 'true'
        run: |
          echo "Error: 'recipe.json' does not match 'Cargo.lock'"
          exit 1
