name: check-lockfiles

on:
  push:
    branches:
      - main
    paths:
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches:
      - main
    paths:
      - Cargo.toml
      - Cargo.lock

jobs:
  publish-recipe-json:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2
        with:
          key: "publish-recipe-json"
      - run: make install-cargo-chef
      - run: make prepare-recipe
      - uses: actions/upload-artifact@v3
        with:
          name: recipe.json
          path: recipe.json

  cargo-unused-dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Read package.json
        id: toolchain
        uses: juliangruber/read-file-action@v1
        with:
          path: ./rust-nightly-toolchain.txt
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.toolchain.outputs.content }}
          profile: minimal
      - uses: Swatinem/rust-cache@v2
        with:
          key: "cargo-unused-dependencies"
      - run: make install-cargo-udeps
      - run: make check-deps
