name: docker

on:
  pull_request:
    branches:
      - main

env:
  IMAGE: jameshiew/hello-http:${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  build-amd64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build --platform linux/amd64 -t $IMAGE-amd64 .
      - run: docker push $IMAGE-amd64

  build-arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build --platform linux/arm64 -t $IMAGE-arm64 .
      - run: docker push $IMAGE-arm64

  push-multiarch-manifest:
    runs-on: ubuntu-22.04
    needs:
      - build-amd64
      - build-arm64
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker manifest create $IMAGE --amend $IMAGE-amd64 --amend $IMAGE-arm64
      - run: docker manifest push --purge $IMAGE
