name: docker

on:
  pull_request:
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build --platform linux/amd64 -t jameshiew/hello-http:latest-amd64 .
      - run: docker push jameshiew/hello-http:latest-amd64

  build-arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build --platform linux/arm64 -t jameshiew/hello-http:latest-arm64 .
      - run: docker push jameshiew/hello-http:latest-arm64

  push-multiarch-manifest:
    runs-on: ubuntu-22.04
    needs:
      - build-amd64
      - build-arm64
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker manifest create jameshiew/hello-http:latest --amend jameshiew/hello-http:latest-amd64 --amend jameshiew/hello-http:latest-arm64
      - run: docker manifest push --purge jameshiew/hello-http:latest
