name: Rust (PR)

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/rust.yml"
      - "rust-toolchain.toml"
      - "**/*.rs"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/rust.yml"
      - "rust-toolchain.toml"
      - "**/*.rs"

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup show
      - run: rustup component add clippy
      - run: rustup component add rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings

  build:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/head/main'
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
