name: rust

on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/rust.yml"
      - "**/*.rs"
      - Cargo.*
      - healthcheck.sh
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/rust.yml"
      - "**/*.rs"
      - Cargo.*
      - healthcheck.sh

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup show
      - run: rustup component add clippy
      - run: rustup component add rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
